### ISSUE TITLE
Unable to compile it with emqttc

### ISSUE THREAD

**Issue by omkarnathsingh** [emqtt/gen_logger#4]
I am getting the following error. Can someone tell a fix for it? 

```
==> gen_logger (compile)
ERROR: Cannot parse OTP Release version string: 17
ERROR: compile failed while processing /builds/test/deps/gen_logger: rebar_abort
Makefile:90: recipe for target 'deps/.built' failed
make: *** [deps/.built] Error 1
ERROR: Job failed: exit code 1
```

**Comment by omkarnathsingh** [comment]
Any solution to it yet?

**Comment by emqplus** [comment]
@omkarnathsingh Do you use Erlang/OTP R17 to build the `emqttc`?

**Comment by omkarnathsingh** [comment]
@emqplus No, I am using Erlang 19 to build. 

To me it seems issue with this line in rebar.config, `{require_min_otp_vsn, "17"}.`

**Comment by emqplus** [comment]
@omkarnathsingh I cannot reproduce the issue. Please comment the line `{require_min_otp_vsn, "17"}`  in rebar.config and try to make `emqttc` again.
